apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: apis.gateway.kyma-project.io
spec:
  versions:
  - name: v1alpha2
    served: true
    storage: true
  - name: v2alpha1
    served: true
    storage: false
