---
apiVersion: gateway.kyma-project.io/v2alpha1
kind: Api
metadata:
  name: passthrough
spec:
  service:
    hostURL: https://imgur.com
    name: imgur
    port: 443
  auth: 
    name: PASSTHROUGH
---
apiVersion: gateway.kyma-project.io/v2alpha1
kind: Api
metadata:
  name: oauth
spec:
  service:
    hostURL: https://imgur.com
    name: imgur
    port: 443
  auth: 
    name: OAUTH
    config:
      - path: /foo
        scopes: [foo, bar]
        methods: [GET]
---
apiVersion: gateway.kyma-project.io/v2alpha1
kind: Api
metadata:
  name: oauth-bad
spec:
  service:
    hostURL: https://imgur.com
    name: imgur
    port: 443
  auth: 
    name: OAUTH
    config: 