---
apiVersion: gateway.kyma-project.io/v2alpha1
kind: Api
metadata:
  name: passthrough-bad-host
spec:
  service:
    host: https://imgur.com
    name: imgur
    port: 443
  auth: 
    name: PASSTHROUGH
  gateway: some-gateway.some-namespace
---
apiVersion: gateway.kyma-project.io/v2alpha1
kind: Api
metadata:
  name: passthrough-bad-gateway
spec:
  service:
    host: imgur.com
    name: imgur
    port: 443
  auth: 
    name: PASSTHROUGH
  gateway: short-name-gateway
---
apiVersion: gateway.kyma-project.io/v2alpha1
kind: Api
metadata:
  name: oauth-bad
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  service:
    host: imgur.com
    name: imgur
    port: 443
  auth: 
    name: OAUTH
    config:
